
# Local copy in your dataset folder

[dyadic_communication]
session_IDs = ["PIS_ID_000", "PIS_ID_02", "PIS_ID_03", "PIS_ID_04", "PIS_ID_05", "PIS_ID_06", "PIS_ID_07", "PIS_ID_08"]
sequence_IDs = ['']
cam_front = 'cam4'
cam_top = 'cam3'
cam_face1 = 'cam1'
cam_face2 = 'cam2'
subjects_descr = ["personL", "personR"]  # implies there are 2 people visible in the video
cam_sees_subjects = {cam1 = [0], cam2 = [1], cam3 = [0, 1], cam4 = [0, 1]}  # order subjects f.l.t.r., indices from subjects_descr, start with 0
path_to_calibrations = "<datasets_folder_path>/dyadic_communication/oslab/calibrations.npz"
data_input_folder = "<datasets_folder_path>/dyadic_communication/<session_ID>/IOI/compressed_25/withAudio"
start_frame_index = 0
fps = 30

[mpi_inf_3dhp]
session_IDs = ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8']
sequence_IDs = ['Seq1', 'Seq2']
cam_front = 'video_8'
cam_top = 'video_5'
cam_face1 = ''
cam_face2 = ''
subjects_descr = ["person"]  # implies that the video shows a single person
cam_sees_subjects = {video_5 = [0], video_8 = [0]}
path_to_calibrations = "<datasets_folder_path>/mpi_inf_3dhp/oslab/calibrations.npz"
data_input_folder = "<datasets_folder_path>/mpi_inf_3dhp/<session_ID>/<sequence_ID>/<camera_name>"
start_frame_index = 1
fps = 50

[communication_multiview]
session_IDs = ["session_xyz"]
sequence_IDs = ['']
cam_front = 'view_center'
cam_top = 'view_top'
cam_face1 = 'view_left'
cam_face2 = 'view_right'
subjects_descr = ["person_left", "person_right"]
cam_sees_subjects = {view_center = [0, 1], view_top = [0, 1], view_left = [0], view_right = [1]} 
path_to_calibrations = "<datasets_folder_path>/NICE_test_datasets/communication_multiview/calibrations.npz"
data_input_folder = "<datasets_folder_path>/NICE_test_datasets/communication_multiview/<session_ID>/"
start_frame_index = 0
fps = 30

[communication_mono]
session_IDs = ["day_1"]
sequence_IDs = ['']
cam_front = 'video'
cam_top = ''
cam_face1 = ''
cam_face2 = ''
subjects_descr = ["Senya", "Johannes"]  
cam_sees_subjects = {video = [0, 1]} 
path_to_calibrations = "<datasets_folder_path>/NICE_test_datasets/communication_mono/calibrations.npz"
data_input_folder = "<datasets_folder_path>/NICE_test_datasets/communication_mono/<session_ID>/"
start_frame_index = 0
fps = 30

[dc_resolution015_fps10_videos]
session_IDs = ['frames']
sequence_IDs = ['']
cam_front = "8700A24"
cam_top = "8700A23"
cam_face1 = ""
cam_face2 = ""
subjects_descr = ["p1", "p2"]  
cam_sees_subjects = {8700A21 = [0], 8700A22 = [1], 8700A23 = [0, 1], 8700A24 = [0, 1]} 
path_to_calibrations = "<datasets_folder_path>/NICE_test_datasets/dc_resolution015_fps10/calibrations.npz"
data_input_folder = "<datasets_folder_path>/NICE_test_datasets/dc_resolution015_fps10/<session_ID>"
start_frame_index = 0
fps = 10

[dc_resolution015_fps10_frames]
session_IDs = ['frames']
sequence_IDs = ['']
cam_front = "8700A24"
cam_top = "8700A23"
cam_face1 = "8700A21"
cam_face2 = "8700A22"
subjects_descr = ["p1", "p2"]  
cam_sees_subjects = {8700A21 = [0], 8700A22 = [1], 8700A23 = [0, 1], 8700A24 = [0, 1]} 
path_to_calibrations = "<datasets_folder_path>/NICE_test_datasets/dc_resolution015_fps10/calibrations.npz"
data_input_folder = "<datasets_folder_path>/NICE_test_datasets/dc_resolution015_fps10/<session_ID>/<camera_name>"
start_frame_index = 0
fps = 10

[20240701_res025_2people_avi]
session_IDs = ['sitting', 'standing']
sequence_IDs = ['']
cam_front = "IOI_03"
cam_top = "IOI_10"
cam_face1 = "IOI_02"
cam_face2 = "IOI_04"
subjects_descr = ["pL", "pR"]  
cam_sees_subjects = {IOI_02 = [0, 1], IOI_03 = [0, 1], IOI_04 = [0, 1], IOI_10 = [0, 1]} 
path_to_calibrations = "<datasets_folder_path>/NICE_test_datasets/20240701_res025_2people_avi/calibrations.npz"
data_input_folder = "<datasets_folder_path>/NICE_test_datasets/20240701_res025_2people_avi/<session_ID>/avi/<camera_name>"
start_frame_index = 0
fps = 30
