# This config supports using placeholders.
# options are <git_hash> <commit_message> <me> <today> <yyyymmdd> <time> <pwd>
# and all keys from your local 'machine_specific_paths.toml' as well as 'io'
# and top layer dictionary entries

visualize = true              # whether to save image/video visualizations of detectors
save_csv = true               # whether to save all results to csv-files

# each component can be assigned to / run with multiple different algorithms
[component_algorithm_mapping]
gaze_individual = ['multiview_eth_xgaze']
gaze_multiview = ['gaze_fusion']
gaze_interaction = ['gaze_distance']
body_joints = ['hrnetw48', 'vitpose']
hand_joints = ['hrnetw48']
face_landmarks = ['hrnetw48']
kinematics = ['velocity_body']
proximity = ['body_distance']
leaning = ['body_angle']
emotion_individual = ['py_feat']
head_orientation = ['spiga']

# define which data to run on
[run]
[run.communication_multiview]
components = ["body_joints", "gaze_individual", "gaze_multiview", "gaze_interaction", "kinematics", "proximity", "emotion_individual", "head_orientation"]
videos = [
   {session_ID = "session_xyz", sequence_ID='', video_start = 0, video_length = 99},
]

[io]
experiment_name = "<yyyymmdd>"                                     # define the name of the experiment (str), default: date as "<yyyymmdd>"
out_folder = "<output_folder_path>/experiments/<experiment_name>"  # define where to save the experiment output (str)
out_sub_folder_name = "<cur_dataset_name>_<cur_session_ID>_s<cur_video_start>_l<cur_video_length>"
out_sub_folder = "<out_folder>/<out_sub_folder_name>"
dataset_properties = "configs/dataset_properties.toml"
detectors_config = "configs/detectors_config.toml"
assets = "<code_folder>/nicetoolbox/detectors/assets"

process_data_to = "data_folder"
data_folder = "<output_folder_path>/nicetoolbox_input/<cur_dataset_name>_<cur_session_ID>_<cur_sequence_ID>"
detector_out_folder = "<out_sub_folder>/<cur_component_name>/<cur_algorithm_name>/detector_output"
detector_visualization_folder = "<out_sub_folder>/<cur_component_name>/<cur_algorithm_name>/visualization"
detector_additional_output_folder = "<out_sub_folder>/<cur_component_name>/<cur_algorithm_name>/additional_output"
detector_run_config_path = "<out_sub_folder>/<cur_component_name>/<cur_algorithm_name>"
detector_final_result_folder = "<out_sub_folder>/<cur_component_name>"
csv_out_folder = "<out_folder>/csv_files"
code_folder = "<pwd>"

log_level = "INFO" # Can be "CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"