[human_pose]
[human_pose.coco_wholebody]
[human_pose.coco_wholebody.keypoints_index]
[human_pose.coco_wholebody.keypoints_index.body]
"nose" = 0
"left_eye" =  1
"right_eye" = 2
"left_ear" = 3
"right_ear" = 4
"left_shoulder" = 5
"right_shoulder" = 6
"left_elbow" = 7
"right_elbow" = 8
"left_wrist" = 9
"right_wrist" = 10
"left_hip" = 11
"right_hip" = 12
"left_knee" = 13
"right_knee" = 14
"left_ankle" = 15
"right_ankle" = 16
[human_pose.coco_wholebody.keypoints_index.foot]
"left_bigtoe" =  17
"left_smalltoe" = 18
"left_heel" = 19
"right_bigtoe" = 20
"right_smalltoe" = 21
"right_heel" = 22
[human_pose.coco_wholebody.keypoints_index.face]
"face_landmarks" =  [23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39] #exclusive last element, i.e. 40
"right_eyebrow" = [40,41,42,43,44]
"left_eyebrow" = [45,46,47,48,49]
"nose_up" = [50,51,52,53]
"nose_down" = [54,55,56,57,58]
"right_eye" = [59,60,61,62,63,64]
"left_eye" = [65,66,67,68,69,70]
"mouth" = [71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90]
[human_pose.coco_wholebody.keypoints_index.hand]
"left_hand" = [91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111]
"right_hand" = [112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132]
[human_pose.coco_wholebody.bodypart_index]
"head" = [0,1,2,3,4]
"upper_body" = [5,6,7,8,9,10]  # Indices of keypoints belonging to the upper body
"lower_body" = [11,12,13,14,15,16]

[human_pose.coco_wholebody.connections]
'body_joints' = [
    ["left_wrist", "left_elbow", "left_shoulder", "left_hip", "left_knee", "left_ankle", "left_bigtoe"],
    ["left_heel", "left_ankle", "left_smalltoe"],
    ["right_wrist", "right_elbow", "right_shoulder", "right_hip", "right_knee", "right_ankle", "right_bigtoe"],
    ["right_heel", "right_ankle", "right_smalltoe"],
    ["left_shoulder", "right_shoulder"],
    ["left_hip", "right_hip"]]

'hand_joints' = [
    ["left_hand_0", "left_hand_2", "left_hand_5", "left_hand_9", "left_hand_13", "left_hand_17", "left_hand_0"],
    ["left_hand_2", "left_hand_4"], ["left_hand_5", "left_hand_8"], ["left_hand_9", "left_hand_12"],["left_hand_13", "left_hand_16"], ["left_hand_17", "left_hand_20"],
    ["right_hand_0", "right_hand_2", "right_hand_5", "right_hand_9", "right_hand_13", "right_hand_17", "right_hand_0"],
    ["right_hand_2", "right_hand_4"], ["right_hand_5", "right_hand_8"], ["right_hand_9", "right_hand_12"],["right_hand_13", "right_hand_16"], ["right_hand_17", "right_hand_20"]]

'face_landmarks' = []


[human_pose.human36m.connections]
'body_joints' = [
    ["head_top", "head", "neck", "spine4", "spine3", "spine2"],
    ["left_wrist", "left_elbow", "left_shoulder", "left_hip", "left_knee", "left_ankle", "left_toe"],
    ["right_wrist", "right_elbow", "right_shoulder", "right_hip", "right_knee", "right_ankle", "right_toe"],
    ["left_shoulder", "right_shoulder"],
    ["left_hip", "right_hip"]]

'hand_joints' = []
'face_landmarks' = []

[human_pose.human36m.keypoints_index]
'spine3' = 0
'spine4' = 1
'spine2' = 2
'spine' = 3
'pelvis'= 4
'neck' = 5
'head' = 6
'head_top' = 7
'left_clavicle' = 8
'left_shoulder' = 9
'left_elbow' = 10
'left_wrist' = 11
'left_hand' = 12
'right_clavicle' = 13
'right_shoulder' = 14
'right_elbow' = 15
'right_wrist' = 16
'right_hand' = 17
'left_hip' = 18
'left_knee' = 19
'left_ankle' = 20
'left_foot' = 21
'left_toe' = 22
'right_hip' = 23
'right_knee' = 24
'right_ankle' = 25
'right_foot' = 26
'right_toe' = 27


[human_pose.bodypart_names]
head = ["nose", "left_eye", "right_eye", "left_ear", "right_ear"]
upper_body = ["left_shoulder", "right_shoulder", "left_elbow", "right_elbow", "left_wrist", "right_wrist"]
lower_body = ["left_hip", "right_hip", "left_knee", "right_knee", "left_ankle", "right_ankle"]

[human_pose.bone_dict]
"eye_distance" = ["left_eye", "right_eye"]
"left_upper_arm" = ["left_shoulder", "left_elbow"]
"left_lower_arm" = ["left_elbow", "left_wrist"]
"right_upper_arm"= ["right_shoulder", "right_elbow"]
"right_lower_arm"= ["right_elbow", "right_wrist"]
"left_upper_leg" = ["left_hip", "left_knee"]
"left_lower_leg" = ["left_knee", "left_ankle"]
"right_upper_leg" = ["right_hip", "right_knee"]
"right_lower_leg"= ["right_knee", "right_ankle"]

[human_pose.joint_diameter_size] #in meter
"left_eye" = 0.025
"right_eye" = 0.025
"nose" = 0.040
"left_ear" = 0.035
"right_ear" = 0.035
"left_shoulder" = 0.070
"right_shoulder" = 0.070
"left_elbow" = 0.065
"right_elbow" = 0.065
"left_wrist" =  0.045
"right_wrist" = 0.045
"left_hip" = 0.075
"right_hip" = 0.075
"left_knee" = 0.080
"right_knee" = 0.080
"left_ankle" = 0.055
"right_ankle" = 0.055
#"left_bigtoe" = 0.030
#"right_bigtoe" = 0.030
#"left_heel" = 0.040
#"right_heel" = 0.040

[head_orientation]
[head_orientation.spiga]
[head_orientation.spiga.keypoints_index.face]
"face_landmarks" =  [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,
    29,30,31,32]
"right_eyebrow" = [33,34,35,36,37,38,39,40,41]
"left_eyebrow" = [42,43,44,45,46,47,48,49,50]
"nose_up" = [51,52,53,54]
"nose_down" = [55,56,57,58,59]
"right_eye" = [60,61,62,63,64,65,66,67]
"left_eye" = [68,69,70,71,72,73,74,75]
"mouth" = [76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95]
"iris_right" = [96]
"iris_left" = [97]

[order]
keypoints = [
    "nose", "left_eye", "right_eye", "left_ear", "right_ear", 'neck', 'head', 'head_top',
    "left_shoulder", "right_shoulder", 'left_clavicle', 'right_clavicle',
    'spine3', 'spine4', 'spine2', 'spine',
    "left_elbow", "right_elbow", "left_wrist", "right_wrist", 'left_hand', 'right_hand',
    "left_hip", "right_hip", 'pelvis', "left_knee", "right_knee",
    'left_foot', 'right_foot', "left_ankle", "right_ankle", "left_heel", "right_heel",
    "left_bigtoe", "right_bigtoe", "left_smalltoe", "right_smalltoe"
    ]
bones = [
    "eye_distance", "left_upper_arm", "left_lower_arm", "right_upper_arm", "right_lower_arm",
    "left_upper_leg", "left_lower_leg", "right_upper_leg", "right_lower_leg"
    ]
microactions = [
    'eyes_eymov', 'eyes_eyga', 'eyes_eybd', 'eyes_eysml', 'eyes_eycry', 'eyes_eyrb', 'eyes_eycl',
    'lips_lsm', 'lips_lau', 'lips_lpu', 'lips_lbi',
    'head_hnod', 'head_hshk', 'head_hmov', 'head_htrn', 'head_hup', 'head_hdn', 'head_hsd',
    'lobo_lgcr', 'lobo_lgucr', 'lobo_fmov',
    'hands_hrep', 'hands_htfa', 'hands_hthd', 'hands_gest', 'hands_htbd', 'hands_hadj', 'hands_note', 'hands_wipe',
    'upbo_flean', 'upbo_blean', 'upbo_shrai',
    'fubo_readj',
    'eyebrows_ebr', 'eyebrows_efrn'
]

[microactions.daya]
'eyes_eymov' = 1
'eyes_eyga' = 2
