run_mode = ["experiment", "development", "production"]
git_hash = 'type:str'
visualize = 'type:bool'

[component_algorithm_mapping]
gaze_individual = 'keys:configs/detectors_config.toml:algorithms'
gaze_interaction = 'keys:configs/detectors_config.toml:algorithms'
body_joints = 'keys:configs/detectors_config.toml:algorithms'
hand_joints = 'keys:configs/detectors_config.toml:algorithms'
face_landmarks = 'keys:configs/detectors_config.toml:algorithms'
kinematics = 'keys:configs/detectors_config.toml:algorithms'
proximity = 'keys:configs/detectors_config.toml:algorithms'
leaning = 'keys:configs/detectors_config.toml:algorithms'

[run]
[run.dyadic_communication]
components = 'keys:configs/run_file_check.toml:component_algorithm_mapping'
[run.dyadic_communication.videos]
session_ID = 'values:configs/dataset_properties.toml:dyadic_communication.session_IDs'
sequence_ID = 'values:configs/dataset_properties.toml:dyadic_communication.sequence_IDs'
video_start = 'type:int'
video_length = 'type:int'
video_skip_frames = 'type:bool'
annotation_interval = 'type:float'

[run.mpi_inf_3dhp]
components = 'keys:configs/run_file_check.toml:component_algorithm_mapping'
[run.mpi_inf_3dhp.videos]
session_ID = 'values:configs/dataset_properties.toml:mpi_inf_3dhp.session_IDs'
sequence_ID = 'values:configs/dataset_properties.toml:mpi_inf_3dhp.sequence_IDs'
video_start = 'type:int'
video_length = 'type:int'
video_skip_frames = 'type:bool'
annotation_interval = 'type:float'


[io]
experiment_name = 'type:str'
out_folder = 'folder:base'
out_sub_folder = 'folder:base'
dataset_config = 'file:'
assets = 'folder:full'

process_data_to = ['data_folder', 'tmp_folder']
data_folder = 'folder:base'
tmp_folder = 'folder:base'
detector_out_folder = 'tbd'
detector_visualization_folder = 'tbd'
detector_additional_output_folder = 'tbd'
detector_tmp_folder = 'tbd'
detector_run_config_path = 'tbd'
detector_final_result_folder = 'tbd'
code_folder = 'folder:full'
conda_path = 'folder:full'
log_level = 'type:int'
